// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_learderboard_test_2 = "CgkI5_nBv9IJEAIQAw"; // <GPGSID>
        public const string achievement_learderboard_test_3 = "CgkI5_nBv9IJEAIQBA"; // <GPGSID>
        public const string achievement_learderboard_test_4 = "CgkI5_nBv9IJEAIQBQ"; // <GPGSID>
        public const string achievement_learderboard_test_5 = "CgkI5_nBv9IJEAIQBg"; // <GPGSID>
        public const string leaderboard_learderboard_test = "CgkI5_nBv9IJEAIQAg"; // <GPGSID>
        public const string achievement_archivement_test = "CgkI5_nBv9IJEAIQAQ"; // <GPGSID>

}

